### ISSUE TITLE
LoadError

### ISSUE THREAD

**Issue by Shmuwol** [lukegrecki/internet_near_me#1]
Hey, just tried using your gem, got a load error, i believe it may be in `internet_near_me/exe/internet_near_me`, you have `require_relative "../config/environment"` that works for Development but it should be changed to `require_relative "../lib/internet_near_me/"` for production

**Comment by lukegrecki** [comment]
Hey Schmully. Thanks for letting me know. Are you getting this error when you are trying to use the gem in the terminal as a CLI or including it in a Gemfile in a project?

**Comment by lukegrecki** [comment]
Nevermind, just replicated it. Working on fixing.

**Comment by lukegrecki** [comment]
Fixed with bfa95600194d3e7cb910b753ad65c3d98e45c683. Let me know if you have any other problems.
